use_frameworks!

platform :ios, '10.0'

target 'DeepmediFaceKit_Example' do
  pod 'DeepmediFaceKit', :path => '../'

  target 'DeepmediFaceKit_Tests' do
    inherit! :search_paths

pod 'Then'
pod 'SnapKit', '~> 5.0.0'
pod 'GoogleMLKit/FaceDetection'
pod 'Alamofire', '~> 5.2'
pod 'OpenCV', '~> 4.3'
pod 'RxSwift', '~> 5'
pod 'RxCocoa', '~> 5'

    
  end
end
