# use_frameworks!
use_frameworks! :linkage > :static

platform :ios, '13.0'

target 'DeepmediFaceKit_Example' do

  pod 'DeepmediFaceKit', :path => '../'

	# pod 'Then'
	pod 'SnapKit', '~> 5.0.0'
	pod 'GoogleMLKit/FaceDetection', '2.6.0'
	pod 'Alamofire', '~> 5.2.0'
	# pod 'OpenCV', '~> 4.3'
	pod 'RxSwift', '~> 6.0.0'
	pod 'RxCocoa', '~> 6.0.0'

  target 'DeepmediFaceKit_Tests' do
    inherit! :search_paths
  end
end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
    end
  end
end

